### PR TITLE
Added the map

### PR DESCRIPTION
**Pull request by BiswajitSahoo-tech**
Fixes [#18 ]
Added the Map using MapBox.
### Map Features

- Map style changes( dark/light) according to the page theme
- Automatic zoom fit to accommodate all the location pointer
- User can pan around
- User can also zoom in and zoom out

### Necessary for map feature to work
**Steps to add a map token from MapBox**
1.  log in to MapBox [https://www.mapbox.com/](url)
2.  Go to the tokens
3.  Create a new one or use the existing one( copy it)
4.  Pest it into the `.env ` file in the `MAP_TOKEN` field

### Optional
1.  You can also change the map style
2.  Go to MapBox studio and design a new map style
3.  And then paste the share link of the style into the `MAP_STYLE` field of `.env` file

### Screenshot
image

image

Note- (Above map data are random and are taken only for the purpose of testing)

### CODE REVIEW

**Comment by BiswajitSahoo-tech** [comment]
Hi @TheRedstoneRadiant,
Please follow the above steps to get an access token for the map and paste it into `.env` file, where the website is hosted.
Thank You

**Comment by BiswajitSahoo-tech** [comment]
Hi @TheRedstoneRadiant,
Any problem? Please tell me if there is an issue with the access token
Please review my PR
Thanks

**Comment by TheRedstoneRadiant** [comment]
Awesome!!!

**Comment by BiswajitSahoo-tech** [comment]
Hi @TheRedstoneRadiant,
I have added a public map token.
There is no more need to create one, and the map feature will be fully functional
Please review my PR and consider merging for Hacktoberfest 2022 :)

**Comment by TheRedstoneRadiant** [comment]
Will do in a bit, but it overall looks good!

**Comment by BiswajitSahoo-tech** [comment]
Thanks @TheRedstoneRadiant ❤️

**Comment by TheRedstoneRadiant** [comment]
Thank you for your patience, code under review.

**Comment by BiswajitSahoo-tech** [comment]
Thanks, @TheRedstoneRadiant ❤️

**Pull request merged**
